DEV-2582 admin login block하는 기능 추가
easi6/server-common pull request #11
Opened 2019-11-25 08:59 UTC by meloning

2019-11-25 12:44 UTC, spica requested changes
전반적으로 인덴트가 본인 에디터 설정이 4로 되어 있는거 같은데,
2로 돌려주시고.
로직이 좀 이상해요. 
Admin인걸 먼저 체크하고, 
admin이면 blocked 된 계정인지 먼저 체크하고, 
key가 이미 존재하는지 유무와 상관 없이
패스워드 틀렸으면 1 더하고 (키 없으면 1로 셋팅)
패스워드 맞으면 0으로 셋팅하면 될 거 같은데
로직 리펙토링좀 해 주세요

2019-11-25 12:44 UTC, spica commented on auth_setup.js
> +            `${namespace}_${refreshToken}`,
인덴트는 왜고치셨어요?
딱히 prettifier가 돈 거 같진 않은데

2019-11-25 12:44 UTC, spica commented on auth_setup.js
> +        let isExistKey = await redisClient.existsAsync(username + '_auth_fail_count');
이건 왜 Admin뿐 아니라 모든 entity에 대해서 체크를 해요?

2019-11-25 12:44 UTC, spica commented on auth_setup.js
> +        let isExistKey = await redisClient.existsAsync(username + '_auth_fail_count');
그리고 할거면 model 명도 키에 들어 가는게 좋을 거 같은데요. 
`${model_name}_${username}_auth_fail_count` 뭐 이런식으로.

2019-11-25 12:44 UTC, spica commented on auth_setup.js
> +          const admin_block = await Admin.findOne({ where: { login: username}});
entity 자체가 이미 find로 찾은 모델인데 여기서 왜 다시 찾아요?

2019-11-25 12:44 UTC, spica commented on auth_setup.js
> +          const admin_block = await Admin.findOne({ where: { login: username}});
그리고 변수명이 왜이래요. 할거면 admin이라고 쓰시지.

2019-11-25 12:44 UTC, spica commented on auth_setup.js
> +        let isExistKey = await redisClient.existsAsync(username + '_auth_fail_count');
그리고 한번쓰고 안변하는 값이면 const 쓰세요

2019-11-25 12:45 UTC, spica commented
그리고 이렇게 common쪽 고치면 
라이더 서버쪽도 같이 영향 받을 거 같은데, 그쪽도 같이 대응해주세요.

2019-11-27 04:55 UTC, spica commented on auth_setup.js
> +      if (model.fields.blocked) {
요거 lodash !_.isNill 함수로 합시다.

2019-11-27 04:55 UTC, spica commented on auth_setup.js
> +      if (model.fields.blocked) {
이것만 고치면 될 듯요.

2019-11-27 05:25 UTC, meloning commented on auth_setup.js
> +      if (model.fields.blocked) {
if (lodash.isNil(model.fields.blocked)) 이렇게 말씀하시는거죠?

2019-11-27 06:08 UTC, spica approved these changes

2019-11-27 06:17 UTC, merged